### ISSUE TITLE
Command edit

### ISSUE THREAD

**Issue by robmonday** [elnobun/Linux-Server-Configuration#6]
Step G4

Do you mean "sudo nano /etc/apache2/sites-enabled/000-default.conf"

...rather than "sudo nano cat /etc/apache2/sites-enabled/000-default.conf" ?

**Comment by elnobun** [comment]
Yes, I actually mean---> sudo nano cat  /etc/apache2/sites-enabled/000-default.conf

That was what actually worked.

When writing that code, there is a space after the _cat_. So you have "sudo nano cat /space\ /etc..."

**Comment by robmonday** [comment]
gotcha...okay, sounds good!

**Comment by elnobun** [comment]
cool 👍
